version: "3.9"

services:
  api:
    build: .
    container_name: issue-tracker-dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app # live reload
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: issue-tracker-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker
    volumes:
      - issue_tracker_dev_data:/var/lib/postgresql/data

volumes:
  issue_tracker_dev_data:
