services:
  api:
    build: .
    container_name: issue-tracker-api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "80:5000" # Production port
    command: gunicorn -w 4 -b 0.0.0.0:5000 run:app

  db:
    image: postgres:16-alpine
    container_name: issue-tracker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker
    volumes:
      - issue_tracker_db:/var/lib/postgresql/data

volumes:
  issue_tracker_db:
